---
abstract: ~
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fedora-App-MaintainerTools
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  CPAN::MetaMuncher:
    file: lib/CPAN/MetaMuncher.pm
    version: 0.001
  Fedora::App::MaintainerTools:
    file: lib/Fedora/App/MaintainerTools.pm
    version: 0.001
  Fedora::App::MaintainerTools::Command::updatespec:
    file: lib/Fedora/App/MaintainerTools/Command/updatespec.pm
    version: 0.001
  Fedora::App::MaintainerTools::Plugin::BuildRequires:
    file: lib/Fedora/App/MaintainerTools/Plugin/BuildRequires.pm
    version: 0.001
  Fedora::App::MaintainerTools::Plugin::CheckForUpdate:
    file: lib/Fedora/App/MaintainerTools/Plugin/CheckForUpdate.pm
    version: 0.001
  Fedora::App::MaintainerTools::Plugin::FedoraBits:
    file: lib/Fedora/App/MaintainerTools/Plugin/FedoraBits.pm
    version: 0.001
  Fedora::App::MaintainerTools::Plugin::First:
    file: lib/Fedora/App/MaintainerTools/Plugin/First.pm
    version: 0.001
  Fedora::App::MaintainerTools::Plugin::Last:
    file: lib/Fedora/App/MaintainerTools/Plugin/Last.pm
    version: 0.001
  Fedora::App::MaintainerTools::Plugins:
    file: lib/Fedora/App/MaintainerTools/Plugins.pm
    version: 0.001
  Fedora::App::MaintainerTools::Types:
    file: lib/Fedora/App/MaintainerTools/Types.pm
    version: 0.001
  Fedora::App::MaintainerTools::UpdateData:
    file: lib/Fedora/App/MaintainerTools/UpdateData.pm
    version: 0.001
requires:
  CPANPLUS::Backend: 0
  DateTime: 0
  File::Copy: 0
  IPC::System::Simple: 0
  Moose: 0
  MooseX::App::Cmd: 0
  MooseX::AttributeHelpers: 0
  MooseX::Log::Log4perl: 0
  MooseX::Types: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  RPM::Spec: 0
  YAML::Tiny: 0
  autodie: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
